### ISSUE TITLE
Instructions for running locally

### ISSUE THREAD

**Issue by maxomatic458** [EthanShoeDev/elden-ring-compass#5]
Im trying to run this project locally, but when running 
```
npm i 
npm run dev
```

i get this error here:
```
> elden-ring-compass@0.0.0 dev
> vite

error when starting dev server:
Error: Missing "./compiler-runtime" specifier in "react" package
...
```

are there some specific instructions i need to follow / do i need to use a specific packet manager?

**Comment by EthanShoeDev** [comment]
Yeah I am using `bun`

You do have to build the wasm parser library before running `bun i`.

I just added a section to readme for contributing.

Thanks for your interest!
